name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14']
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: ${{ matrix.python-version }}
      - uses: astral-sh/ruff-action@278981a28ce3188b1e39527901f38254bf3aac89 # v4.1.0
        with:
          args: "--version"
          src: bin/
          version: ">=0.16.0"
      - run: ruff check
      - run: ruff format --check --diff
      - name: Lint with shellcheck
        uses: ludeeus/action-shellcheck@00cae500b08a931fb5698e11e79bfbd38e612a38 # v2.0.0
        with:
          check_together: "yes"
      - name: Run tests
        run: |
          bin/test
  jsdelivrpurge:
    name: Purge jsDelivr cache
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    needs: build
    if: ${{ always() && github.event_name == 'push' && github.ref_name == 'master' && needs.build.result == 'success' }}
    steps:
      - name: Run jsDelivr-Purge
        uses: List-KR/jsdelivr-purge@5.5.0